turtle.pth:
  build_time: 2021-02-23-15-36-15
  labels:
    Donatello: 0
    Leonardo: 1
    Michelangelo: 2
  loader:
    batch_size: 8
    num_workers: 0
    shuffle: true
  purpose: classifier
  train:
    accuracy: 1.0
    epochs: 10
    learning_rate: 0.001
    model: custom
    momentum: 0.09
    train_time: 194.45
    use_cuda: false
    gpu_model: false
turtle_pretrainm2_gpu.pth:
  build_time: 2021-02-23-15-36-15
  labels:
    Donatello: 0
    Leonardo: 1
    Michelangelo: 2
  loader:
    batch_size: 8
    num_workers: 0
    shuffle: true
  purpose: classifier
  train:
    accuracy: 1.0
    epochs: 10
    learning_rate: 0.001
    model: pretrained
    momentum: 0.09
    train_time: 194.45
    use_cuda: false
    gpu_model: true
